### ISSUE TITLE
httr2::request_perform_iterative

### ISSUE THREAD

**Issue by jimrothstein** [r4ds/bookclub-wapir#51]
This applies more to httr2, than wapir:

I found documentation on **httr2::request_perform_iterative** and related to be on light side and not as clear I would like.

Terminology like "callback function"  or "task handler"  are used frequently in programming.   But **my vague idea** of what the author means and what the author **really means** may not always match.

I think it is best to use proper terminology (we are all adult, yes?)  but urge use of clear definition and/or examples.

In older version **httr** I wrote a loop to handle pagination.   It was ugly and probably inefficient - but I understood it.  Maybe another way to view this is   sometimes **fancy code can obscure details and sometimes details really do count.**

**Comment by jonthegeek** [comment]
req_perform_iterative() is definitely fairly new, and far from perfect, especially on the documentation side! I intend to submit some PRs soonish, now that I've played with it quite a lot.

The intention of that functionality is to let users implement pagination without having to know every possible quirk. You shouldn't have to be an API expert in order to work with APIs. Unfortunately it's not quite there yet, but I think that's a useful intention.
